// Firebase options stub — real values are generated by FlutterFire CLI.
//
// USER ACTION REQUIRED:
//   1. Install FlutterFire CLI (if not already installed):
//        dart pub global activate flutterfire_cli
//
//   2. Run from the soslogistics_flutter directory:
//        flutterfire configure --project=sos-6b1be
//      Select the Android platform and package name: com.sossss.logistics
//      This generates:
//        - android/app/google-services.json
//        - lib/firebase_options.dart  (this file, overwritten with real keys)
//
//   3. Run `flutter pub get` and rebuild.
//
// Until step 2 is completed, the app guards against calling
// Firebase.initializeApp() with REPLACE_ME values — see main.dart.
//
// Do NOT commit google-services.json to version control.

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for platform: '
            '$defaultTargetPlatform. Run flutterfire configure.');
    }
  }

  // Shared Firebase project (sos-6b1be) with the farmer app, so the existing
  // sos_web service account (sos-farmer.json) can deliver pushes to this app too.
  // Uses the farmer Firebase Android app (package com.sosfarmer.app); the build
  // applicationId is aligned to match google-services.json.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmxmaKVuCx-oG6gcR13qZkYKhMTwcoPYQ',
    appId: '1:954237017102:android:8152f5ff73c4edd419305f',
    messagingSenderId: '954237017102',
    projectId: 'sos-6b1be',
    storageBucket: 'sos-6b1be.firebasestorage.app',
  );
}
