// Firebase options stub — real values are generated by FlutterFire CLI.
//
// USER ACTION REQUIRED:
//   1. Install FlutterFire CLI (if not already installed):
//        dart pub global activate flutterfire_cli
//
//   2. Run from the soslogistics_flutter directory:
//        flutterfire configure --project=sos-6b1be
//      Select the Android platform and package name: com.sossss.logistics
//      This generates:
//        - android/app/google-services.json
//        - lib/firebase_options.dart  (this file, overwritten with real keys)
//
//   3. Run `flutter pub get` and rebuild.
//
// Until step 2 is completed, the app guards against calling
// Firebase.initializeApp() with REPLACE_ME values — see main.dart.
//
// Do NOT commit google-services.json to version control.

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for platform: '
            '$defaultTargetPlatform. Run flutterfire configure.');
    }
  }

  // REPLACE_ME values below — run `flutterfire configure --project=sos-6b1be`
  // targeting package com.sossss.logistics to get real values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'sos-6b1be',
    storageBucket: 'REPLACE_ME',
  );
}
